---
- name: Wireguard autoconfiguration
  hosts: headquarters
  gather_facts: 'no'
  connection: network_cli

  tasks:
    - name: Global configuration wireguard
      vyos_config:
        lines:
          - set interfaces wireguard wg1 private-key "{{ lookup('file', inventory_hostname ~ '.2.key') }}"
          - set interfaces wireguard wg1 description 'SDWAN-BCK'
          - set interfaces wireguard wg1 port 51821
        save: true

- name: Wireguard HQ
  hosts: hq
  gather_facts: 'no'
  connection: network_cli

  tasks:
    - name: Global configuration wireguard
      vyos_config:
        lines:
          - set interfaces wireguard wg1 address 10.10.20.1/24
          - set interfaces wireguard wg1 peer sede1 allowed-ips 10.10.20.2/32
          - set interfaces wireguard wg1 peer sede1 public-key "{{ lookup('file', 'sede1.2.pub' ) }}"
          - set interfaces wireguard wg1 peer sede2 allowed-ips 10.10.20.3/32
          - set interfaces wireguard wg1 peer sede2 public-key "{{ lookup('file', 'sede2.2.pub' ) }}"
          - set interfaces wireguard wg1 peer sede3 allowed-ips 10.10.20.4/32
          - set interfaces wireguard wg1 peer sede3 public-key "{{ lookup('file', 'sede3.2.pub' ) }}"
          - set interfaces wireguard wg1 peer sede4 allowed-ips 10.10.20.5/32
          - set interfaces wireguard wg1 peer sede4 public-key "{{ lookup('file', 'sede4.2.pub' ) }}"
        save: true

- name: Wireguard headquarters1
  hosts: sede1, sede2, sede3, sede4
  gather_facts: 'no'
  connection: network_cli

  tasks:
    - name: Global configuration wireguard
      vyos_config:
        lines:
          - set interfaces wireguard wg1 address {{ wg_ip2 }}
          - set interfaces wireguard wg1 peer hq public-key '{{ lookup('file', 'hq.2.pub') }}'
          - set interfaces wireguard wg1 peer hq address 192.168.1.231
          - set interfaces wireguard wg1 peer hq port 51821
          - set interfaces wireguard wg1 peer hq persistent-keepalive 25
          - set interfaces wireguard wg1 peer hq allowed-ips 0.0.0.0/0
        save: true
