- name: Limpiar configuración BGP por completo
  hosts: headquarters
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Eliminar nodo de protocolos BGP
      vyos_config:
        lines:
          - "delete protocols bgp"
        save: yes
